language: node_js
node_js:
  - 6.14.11
script:
  - "npm run build"
  - "npm run test:nowatch"

  deploy:
    provider: heroku
    api_key: 
      secure: $HEROKU
    app: demo-book-store-client-weihan
    